name: Build

on:
  push:
    branches:
      - 'main'
      - 'release'
      - 'release/*'
      - 'release-*'
      - 'haha*'

env:
  NODE_VERSION: 12.15.0
  # Force a path with spaces and to test extension works in these scenarios
  # Unicode characters are causing 2.7 failures so skip that for now.
  special-working-directory: './path with spaces'
  special-working-directory-relative: 'path with spaces'
  # Use the mocha-multi-reporters and send output to both console (spec) and JUnit (mocha-junit-reporter).
  # Also enables a reporter which exits the process running the tests if it haven't already.
  MOCHA_REPORTER_JUNIT: true

jobs:
  setup:
    name: Set up
    # github.repository == 'microsoft/vscode-python'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: python
    outputs:
      vsix_name: ${{ steps.vsix_names.outputs.vsix_name }}
      vsix_artifact_name: ${{ steps.vsix_names.outputs.vsix_artifact_name }}
    steps:
      - name: VSIX names
        id: vsix_names
        run: |
          import os
          if os.environ["GITHUB_REF"].endswith("/main"):
            vsix_type = "insiders"
          else:
            vsix_type = "release"
          print(f"::set-output name=vsix_name::ms-python-{vsix_type}.vsix")
          print(f"::set-output name=vsix_artifact_name::ms-python-{vsix_type}-vsix")

  build-vsix:
    name: Build VSIX
    # github.repository == 'microsoft/vscode-python'
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Use Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Build VSIX
        uses: ./.github/actions/build-vsix
        id: build-vsix

      - name: Rename VSIX
        if: steps.build-vsix.outputs.path != needs.setup.outputs.vsix_name
        run: mv ${{ steps.build-vsix.outputs.path }} ${{ needs.setup.outputs.vsix_name }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ needs.setup.outputs.vsix_artifact_name }}
          path: ${{ needs.setup.outputs.vsix_name }}
          if-no-files-found: error
          retention-days: 14
