name: My Workflow

on:
  issues:
    types:
      - labeled

jobs:
  community-feedback-auto-comment:
    - name: Checkout Actions
      uses: actions/checkout@v3
      with:
        repository: 'karrtikr/vscode-python-github-actions'
        path: ./actions
    - name: Install Actions
      run: npm install --production --prefix ./actions
    - name: Add community feedback auto comment if applicable
      uses: ./actions/community-feedback-auto-comment
