name: PR/CI Check

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - release*

env:
  NODE_VERSION: 16.17.1
  PYTHON_VERSION: '3.10' # YML treats 3.10 the number as 3.1, so quotes around 3.10
  MOCHA_REPORTER_JUNIT: true # Use the mocha-multi-reporters and send output to both console (spec) and JUnit (mocha-junit-reporter). Also enables a reporter which exits the process running the tests if it haven't already.
  ARTIFACT_NAME_VSIX: ms-python-insiders-vsix
  VSIX_NAME: ms-python-insiders.vsix
  TEST_RESULTS_DIRECTORY: .
  # Force a path with spaces and to test extension works in these scenarios
  # Unicode characters are causing 2.7 failures so skip that for now.
  special-working-directory: './path with spaces'
  special-working-directory-relative: 'path with spaces'

jobs:
  lint:
    name: Lintasd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: 'microsoft/vscode-python-engineering'
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Checkout Actions
        uses: actions/checkout@v3
      - name: Lint
        uses: ./.github/actions/lint
        with:
          node_version: ${{ env.NODE_VERSION }}

  check-types:
    name: Check Python types
    runs-on: ubuntu-latest
    steps:
      - name: Use Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install base Python requirements
        uses: brettcannon/pip-secure-install@v1
        with:
          options: '-t ./pythonFiles/lib/python --no-cache-dir --implementation py'

      - name: Install Jedi requirements
        uses: brettcannon/pip-secure-install@v1
        with:
          requirements-file: './pythonFiles/jedilsp_requirements/requirements.txt'
          options: '-t ./pythonFiles/lib/jedilsp --no-cache-dir --implementation py'

      - name: Install other Python requirements
        run: |
          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade --pre debugpy
          python -m pip install --upgrade -r build/test-requirements.txt

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          working-directory: 'pythonFiles'
